#!/usr/bin/env python
# CRON job for md Stripe Cache Monitoring
#
# See: https://www.pitt-pladdy.com/blog/_20160309-081028_0000_Linux_md_RAID5_6_Stripe_Cache_monitoring_on_Cacti_vi_SNMP/
#
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import sys
import os
import time
import csv


# check args
if len(sys.argv) != 3:
	sys.exit ( "Usage: %s <statsfile path> <Device|Description|95th|99th|max>\n" % sys.argv[0] )
statsfile = sys.argv[1]
metric = sys.argv[2]

# sanity check file
timelimit = time.time () - 600
if not os.path.isfile ( statsfile ) or os.stat ( statsfile ).st_mtime < timelimit:
	sys.exit ( "ERROR: stats file \"%s\" too old or doesn't exist\n" % statsfile )

# read in data
with open ( statsfile, 'rt' ) as f:
	csvr = csv.DictReader ( f )
	for value in csvr:
		print value[metric]



