#!/usr/bin/env python


import sys
import os
import time
import glob
import csv
import math


# check args
if len(sys.argv) != 4:
	sys.exit ( "Usage: %s <statsfile path> <run for seconds> <sample interval seconds>\n" % sys.argv[0] )
statsfile = sys.argv[1]
tempfile = '%s.TMP-%d' % (statsfile,os.getpid())
runfor = float(sys.argv[2])
interval = float(sys.argv[3])

# work out timing
starttime = time.time ()
endtime = starttime + runfor

# discover storage to watch and stripe_cache_size (constant)
mddevices = [ os.path.dirname(f).split('/')[3] for f in glob.glob ( '/sys/block/md*/md/stripe_cache_size' ) ]
cachesizes = {}
cacheactives = {}
for dev in mddevices:
	with open ( os.path.join ( '/sys/block', dev, 'md/stripe_cache_size' ) ) as f:
		cachesizes[dev] = int( f.read() )
		f.close()
	cacheactives[dev] = []

# sample loop
nexttime = starttime
while nexttime < endtime:
	for dev in mddevices:
		with open ( os.path.join ( '/sys/block', dev, 'md/stripe_cache_active' ) ) as f:
			cacheactives[dev].append ( int( f.read() ) )
			f.close()
	nexttime = nexttime + interval
	time.sleep ( nexttime - time.time () )

# output percentiles
with open ( tempfile, 'wt' ) as f:
	csvw = csv.writer ( f )
	csvw.writerow ( ['Device','95th','99th','max'] )
	for dev in mddevices:
		data = sorted ( cacheactives[dev] )
		i95 = int ( math.ceil ( float(len(data)-1) * 0.95 ) )
		i99 = int ( math.ceil ( float(len(data)-1) * 0.99 ) )
		csvw.writerow ( [
				dev,
				float(data[i95]) / cachesizes[dev] * 100.,
				float(data[i99]) / cachesizes[dev] * 100.,
				float(data[-1]) / cachesizes[dev] * 100.,
			] )
os.rename ( tempfile, statsfile )


